# Autogenerated wrapper script for blaspp_jll for x86_64-apple-darwin
export libblaspp

using CompilerSupportLibraries_jll
using OpenBLAS32_jll
JLLWrappers.@generate_wrapper_header("blaspp")
JLLWrappers.@declare_library_product(libblaspp, "@rpath/libblaspp.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, OpenBLAS32_jll)
    JLLWrappers.@init_library_product(
        libblaspp,
        "lib/libblaspp.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
